apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hzh0k8vt1-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hzh0k8vt1-java-springboot-gitops